task-1: ✅ basics of testing
VladOSIO2/electronics-stock pull request #1
Opened 2023-03-06 15:54 UTC by VladOSIO2

Created a simple Item class, that represents an item in the stock. Covered it with JUnit unit tests. Implemented unit test run with coverage report for each commit in PR

2023-03-06 16:19 UTC, viktoriaobukhova requested changes

2023-03-06 16:19 UTC, viktoriaobukhova commented on src/main/java/org/stock/item/Item.java
> +    if (weight < 1000) {
1000 looks like magic number - please extract it to the constant

2023-03-06 16:19 UTC, viktoriaobukhova commented on src/main/java/org/stock/item/Item.java
> +    return weight / 1000 + "kg" + weight % 1000 + "g";
the same for "g"/"kg"- please extract it to the constants

2023-03-06 16:40 UTC, VladOSIO2 commented on src/main/java/org/stock/item/Item.java
> +    if (weight < 1000) {
That makes sense. I will extract it to the constant and clean up the code. Thought about making some sample code with some unit test to implement the test run and coverage report for the PRs first, what apparently was a mistake

2023-03-06 16:40 UTC, VladOSIO2 commented on src/main/java/org/stock/item/Item.java
> +    return weight / 1000 + "kg" + weight % 1000 + "g";
Ok, same as above, will extract all of these magic variables to the constants

2023-03-07 08:38 UTC, VladOSIO2 commented
After spending some time on learning the Gradle and workflows, fixed the test run & coverage report. Now after each commit, git workflow will run all the tests and report the test coverage for all affected by PR classes. Workflow check will fail, if any of the tests is failing.

2023-03-07 08:59 UTC, VladOSIO2 commented
Moved the "magic variables" to the proper constants. Although I have a question: despite the first task requires the creation of single class, will that be a better practice to move this responsibility (calculations of the weight & constants used in it) to another class, something like "WeightFormatter"? And calling the weight formatting method inside the Item's corresponding method, providing the Item's weight to WeightFormatter's method

2023-03-07 09:27 UTC, viktoriaobukhova commented
> sure, moving the responsibility to another class that would be responsible for some common actions is definately a good practice 



> Moved the "magic variables" to the proper constants. Although I have a question: despite the first task requires the creation of single class, will that be a better practice to move this responsibility (calculations of the weight & constants used in it) to another class, something like "WeightFormatter"? And calling the weight formatting method inside the Item's corresponding method, providing the Item's weight to WeightFormatter's method

2023-03-07 09:28 UTC, viktoriaobukhova approved these changes

2023-03-07 09:33 UTC, merged

2023-03-07 09:34 UTC, VladOSIO2 commented
Forgot to squash the commits(